- name: Check if Docker is installed
  command: docker --version
  register: docker_installed
  ignore_errors: yes
  changed_when: false

- name: Install Docker dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
  when: docker_installed.rc != 0

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: docker_installed.rc != 0

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  when: docker_installed.rc != 0

- name: Install Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes
  when: docker_installed.rc != 0

- name: Ensure Docker is running
  systemd:
    name: docker
    state: started
    enabled: yes